export const Conveyor = [
  {
    id: 1,
    name: "Malay Kalavadia",
    designation: "Secretary",
    email: "asndkas@gmal.com",
    ph_No: "99019202332",
    linkedIn: "asmnkdas",
  },
  {
    id: 2,
    name: " Abhishek Kumar",
    designation: "Additional Secretary",
    email: "asndkas@gmal.com",
    ph_No: "99019202332",
    linkedIn: "asmnkdas",
  },
  {
    id: 3,
    name: "Sankalp Raj",
    designation: "Additional Secretary",
    email: "asndkas@gmal.com",
    ph_No: "99019202332",
    linkedIn: "asmnkdas",
  },
];

export const Coordinator = [
  {
    id: 1,
    name: "Malay Kalavadia",
    designation: "Secretary",
    email: "asndkas@gmal.com",
    ph_No: "99019202332",
    linkedIn: "asmnkdas",
  },
  {
    id: 2,
    name: "Sankalp Raj",
    designation: "Additional Secretary",
    email: "asndkas@gmal.com",
    ph_No: "99019202332",
    linkedIn: "asmnkdas",
  },
  {
    id: 3,
    name: "Sankalp Raj",
    designation: "Additional Secretary",
    email: "asndkas@gmal.com",
    ph_No: "99019202332",
    linkedIn: "asmnkdas",
  },
  {
    id: 4,
    name: "Malay Kalavadia",
    designation: "Secretary",
    email: "asndkas@gmal.com",
    ph_No: "99019202332",
    linkedIn: "asmnkdas",
  },
  {
    id: 5,
    name: "Sankalp Raj",
    designation: "Additional Secretary",
    email: "asndkas@gmal.com",
    ph_No: "99019202332",
    linkedIn: "asmnkdas",
  },
  {
    id: 6,
    name: "Sankalp Raj",
    designation: "Additional Secretary",
    email: "asndkas@gmal.com",
    ph_No: "99019202332",
    linkedIn: "asmnkdas",
  },
  {
    id: 7,
    name: "Malay Kalavadia",
    designation: "Secretary",
    email: "asndkas@gmal.com",
    ph_No: "99019202332",
    linkedIn: "asmnkdas",
  },
  {
    id: 8,
    name: "Sankalp Raj",
    designation: "Additional Secretary",
    email: "asndkas@gmal.com",
    ph_No: "99019202332",
    linkedIn: "asmnkdas",
  },
];
